### PR TITLE
Statuses should not be cached

### LINKED ISSUE #8: Deactivated nodes still appear
Nodes deactivated in the PuppetDB are still listed in the metrics. They only disappear when restarting the service.

### PR DESCRIPTION
**Pull request by raphink**
Attempt to fix #8

### CODE REVIEW

**Comment by raphink** [comment]
This does not fix #8. There's probably another level of cache.

**Comment by raphink** [comment]
Any idea @cryptobioz ?

**Comment by cryptobioz** [comment]
> There's probably another level of cache.

It's still a bit unclear for me but yes, the Prometheus client caches all the metrics. However, you have two ways to remove them:
- If you want to remove an entire metric vector, you can use the [`MetricVec.Reset`](https://godoc.org/github.com/prometheus/client_golang/prometheus#MetricVec.Reset) function.
- If you want to remove a metric with a specific label, you can use the [`MetricVec.Delete`](https://godoc.org/github.com/prometheus/client_golang/prometheus#MetricVec.Delete) function.

**Comment by raphink** [comment]
That encourages me to stick to my KISS approach on other projects https://github.com/camptocamp/aws-iam-authenticator-proxy/blob/master/main.go#L12

😜

**Comment by cryptobioz** [comment]
Well, I'm not sure which one is the most _KISS_ in fact... ;)

If you have very basic needs, yes, you can build your own metrics and expose them. It's fine for Gauges but it gonna be much more difficult to use Summaries or Histograms.
At the end, the Prometheus client is just a library. Yes, you can do everything manually but it's easier and cleaner to use a dedicated abstraction.

**Comment by raphink** [comment]
@cryptobioz Are you able to have a look at this please? We've had issues with this bug recently (see with @cburki).

**Comment by cryptobioz** [comment]
No problem, I'll have a look at this :)

**Comment by cryptobioz** [comment]
The issue #8 has been fixed by https://github.com/camptocamp/prometheus-puppetdb-exporter/commit/9a3ae38da2b340c5ff51a99d6b66e6df5147adda.

**Pull request closed without merging**
